com.oplus.gr.mode.support=1
com.oplus.camera.mode.data.db.version=102
com.oplus.available.gr.mode.zoomvalues=0.6(14),1(23),2(47),3(70),6(139),10(230)
com.oplus.gr.mode.marked.zoomvalues=1.2173913(28),1.7391304(40)
com.oplus.camera.capture.hdr.cap.mode.value=common,portrait,professional,night,highPixel,xpan,underWater,telephoto,gr,retroCamera
com.oplus.camera.preview.hdr.cap.mode.value=common,professional,night,highPixel,xpan,underWater,telephoto,gr
com.oplus.feature.retro.camera.support=1
com.oplus.flashlevel.configurable.support=1
com.oplus.feature.tilt.shift.photo.support=1
