com.oplus.gr.mode.support=1
com.oplus.camera.mode.data.db.version=103
com.oplus.available.gr.mode.zoomvalues=0.6(16),1(24),3.5(85),7(170)
com.oplus.gr.mode.marked.zoomvalues=1.1666667(28),1.6666667(40)
com.oplus.camera.capture.hdr.cap.mode.value=professional,gr,retroCamera
com.oplus.camera.preview.hdr.cap.mode.value=common,professional,night,highPixel,underWater
com.oplus.feature.retro.camera.support=1
com.oplus.flashlevel.configurable.support=1
com.oplus.feature.tilt.shift.photo.support=1
com.oplus.feature.colorful.screen.torch.config=100
